CREATE DATABASE SERVICE_MARKET
USE SERVICE_MARKET

/*CREACION DE LA TABLA ROLES*/
CREATE TABLE ROLES(
ID_ROL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_ROL VARCHAR(40) NOT NULL)

/*INSERT TABLA ROLES*/
INSERT INTO ROLES(NOMBRE_ROL) VALUES ('ADMINISTRADOR'),('PRESTADOR_SERVICIOS'),('CLIENTE')

SELECT * FROM ROLES 

/*CREACION DE LA TABLA CIUDAD*/
CREATE TABLE CIUDAD(
ID_CIUDAD INT PRIMARY KEY IDENTITY(1,1),
NOMBRE_CIUDAD VARCHAR(50) NOT NULL)

/*INSERT TABLA ROLES*/
INSERT INTO CIUDAD(NOMBRE_CIUDAD) VALUES ('MEDELLIN'),('CALDAS'),('BARBOSA'),('SABANETA'),('LA ESTRELLA'),('ITAGUI'),
('ENVIGADO'),('BELLO'),('GIRARDOTA'),('COPACABANA')

SELECT * FROM CIUDAD

/*CREACION DE LA TABLA USUARIOS*/
CREATE TABLE USUARIOS(
N_IDENTIFICACION VARCHAR(15) PRIMARY KEY,
TIPO_DOC VARCHAR(40) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
FECHA_EXPEDICION DATE NOT NULL,
NOMBRE_USU VARCHAR(60) NOT NULL,
APELLIDOS_USU VARCHAR(70) NOT NULL,
CELULAR_USU VARCHAR(12) NOT NULL,
CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
CONTRASENA VARCHAR(500) NOT NULL,
GENERO VARCHAR(80) NOT NULL,
ID_CIUDAD_FK INT REFERENCES CIUDAD(ID_CIUDAD),
DIRECCION VARCHAR(200) NOT NULL
)

SELECT * FROM USUARIOS

/*CREACION DE LA TABLA INTERMEDIA ASIGNACION_ROL*/
CREATE TABLE ASIGNACION_ROL(
ID_ROL_FK INT REFERENCES ROLES(ID_ROL) DEFAULT 3,
IDENTIFICACION_U_FK VARCHAR(15) REFERENCES USUARIOS(N_IDENTIFICACION)
)

SELECT * FROM ASIGNACION_ROL

/*PROCEDIMIENTO ALMACENADO PARA REGISTRAR USUARIOS*/
CREATE PROCEDURE REGISTRAR_USUARIO(
@TIPO_DOC VARCHAR(40),
@N_IDENTIFICACION VARCHAR(15),
@FECHA_NACIMIENTO DATE,
@FECHA_EXPEDICION DATE,
@NOMBRE_USU VARCHAR(60),
@APELLIDOS_USU VARCHAR(70),
@CELULAR_USU VARCHAR(12),
@GENERO VARCHAR(80),
@ID_CIUDAD_FK INT,
@DIRECCION VARCHAR(200),
@CORREO_ELECTRONICO VARCHAR(100),
@CONTRASENA VARCHAR(500),
@REGISTRADO BIT OUTPUT,
@MENSAJE VARCHAR(100) OUTPUT)
AS 
BEGIN
	IF(NOT EXISTS(SELECT * FROM USUARIOS WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO))
	BEGIN 
		INSERT INTO USUARIOS(N_IDENTIFICACION,TIPO_DOC,FECHA_NACIMIENTO,FECHA_EXPEDICION,NOMBRE_USU,APELLIDOS_USU,CELULAR_USU,CORREO_ELECTRONICO,CONTRASENA,GENERO,ID_CIUDAD_FK,DIRECCION)
		VALUES (@N_IDENTIFICACION,@TIPO_DOC,@FECHA_NACIMIENTO,@FECHA_EXPEDICION,@NOMBRE_USU,@APELLIDOS_USU,@CELULAR_USU,@CORREO_ELECTRONICO,@CONTRASENA,@GENERO,@ID_CIUDAD_FK,@DIRECCION)
		SET @REGISTRADO = 1
		SET @MENSAJE = 'Usuario registrado'
	END
	ELSE
	BEGIN
		SET @REGISTRADO = 0
		SET @MENSAJE = 'Correo ya existe'
	END
END

/*PROCEDIMIENTO ALMACENADO PARA VALIDAR USUARIOS*/
CREATE PROCEDURE VALIDAR_USUARIO(
@CORREO_ELECTRONICO VARCHAR(100),
@CONTRASENA VARCHAR(500))
AS
BEGIN
	IF(EXISTS(SELECT * FROM USUARIOS WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO AND CONTRASENA = @CONTRASENA))
		SELECT * FROM USUARIOS WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO AND CONTRASENA = @CONTRASENA
	ELSE
		SELECT '0'
END

/*EJEMPLO DEL PROCEDIMIENTO ALMACENADO VALIDAR_USUARIO*/
EXEC VALIDAR_USUARIO 'yeyerojas1308@gmail.com','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3'

/*DECLARAR VARIABLES DE SALIDA*/
DECLARE @REGISTRADO BIT, @MENSAJE VARCHAR(100)
/*REGISTRO DE ADMINISTRADORES*/
EXEC REGISTRAR_USUARIO 'CEDULA DE CIUDADANIA','1013376602','2004-01-13','2022-01-14','YESENIA','QUEJADA ROJAS','3135293264','FEMENINO',8,'CALLE 22 CARRERA 61 AA 51','yeyerojas1308@gmail.com','a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',@REGISTRADO OUTPUT,@MENSAJE OUTPUT

/*CREACION DE LA TABLA CATEGORIAS*/
CREATE TABLE CATEGORIAS(
ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_CAT VARCHAR(MAX) NOT NULL,
DESCRIPCION_CAT VARCHAR(MAX) NOT NULL)

SELECT * FROM CATEGORIAS

/*INSERT TABLA CATEGORIAS*/
INSERT INTO CATEGORIAS(NOMBRE_CAT,DESCRIPCION_CAT) VALUES 
('MANTENIMIENTO','ORIENTADA A SOLUCIONAR Y PREVENIR LAS POSIBLES AVERÍAS QUE PUEDA HABER EN EQUIPOS, MÁQUINAS E INSTALACIONES PARA CONSERVAR Y GARANTIZAR SU ÓPTIMO FUNCIONAMIENTO.'),
('TRABAJOS DOMÉSTICOS','TODA LA AYUDA DOMÉSTICA QUE NECESITAS EN CASA CON EXPERTAS EN ORDEN, LIMPIEZA Y DESINFECCIÓN.'),
('REMODELACIÓN Y ALBAÑILERÍA','ORIENTADA EN LA CONSTRUCCIÓN, RENOVACIÓN Y REPARACIÓN DE ESTRUCTURAS, PAREDES, MUROS, PARTES DE EDIFICIOS, CASAS Y MÁS.'),
('SALUD Y BELLEZA','ORIENTADA A LA PRESTACIÓN DE SERVICIOS DESDE LOS DIFERENTES CAMPOS DE LA SALUD Y LA BELLEZA COMO LO SON CORTES, PEINADOS, MAQUILLAJES, MANICURE, PEDICURA, MASAJES, ETC.')

/*CREACION DE LA TABLA SERVICIOS*/
CREATE TABLE SERVICIOS(
ID_SERVICIO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE_SER VARCHAR(70) NOT NULL,
PRECIO_SER DECIMAL NOT NULL,
DESCRIPCION_BREVE VARCHAR(500) NOT NULL,
TERMINOS_SER VARCHAR(MAX) NOT NULL,
ID_CATEGORIA_FK INT REFERENCES CATEGORIAS(ID_CATEGORIA)
)

SELECT * FROM SERVICIOS

/*CREACION DE LA TABLA DETALLE_SERVICIOS(PUBLICACION)*/
CREATE TABLE DETALLE_SERVICIOS(
ID_SERVICIO_FK INT REFERENCES SERVICIOS(ID_SERVICIO),
IDENTIFICACION_U_FK VARCHAR(15) REFERENCES USUARIOS(N_IDENTIFICACION),
FECHA_INICIO DATE NOT NULL DEFAULT GETDATE(),
FECHA_FIN DATE NOT NULL,
ESTADO_DS VARCHAR(20) DEFAULT 'ACTIVO')

SELECT * FROM DETALLE_SERVICIOS

/*PROCEDIMIENTO ALMACENADO PARA CREAR SERVICIOS*/
CREATE PROCEDURE CREAR_SERVICIOS(
@NOMBRE_SER VARCHAR(70),
@PRECIO_SER DECIMAL,
@DESCRIPCION_BREVE VARCHAR(500),
@TERMINOS_SER VARCHAR(MAX),
@ID_CATEGORIA_FK INT
)
AS 
BEGIN
	INSERT INTO SERVICIOS(NOMBRE_SER,PRECIO_SER,DESCRIPCION_BREVE,TERMINOS_SER,ID_CATEGORIA_FK) 
	VALUES (@NOMBRE_SER,@PRECIO_SER,@DESCRIPCION_BREVE,@TERMINOS_SER,@ID_CATEGORIA_FK)
END

/*PROCEDIMIENTO ALMACENADO PARA CONSULTAR SERVICIOS*/
CREATE PROCEDURE CONSULTAR_SERVICIOS
AS 
BEGIN
	SELECT NOMBRE_SER, PRECIO_SER, DESCRIPCION_BREVE, NOMBRE_CAT FROM 
	SERVICIOS INNER JOIN CATEGORIAS 
	ON SERVICIOS.ID_CATEGORIA_FK = CATEGORIAS.ID_CATEGORIA
END

EXEC CONSULTAR_SERVICIOS

/*VISTA MAS INFORMACION SOBRE LA PUBLICACION DEL SERVICIO
TABLAS: DETALLE_SERVICIOS // SERVICIOS // CATEGORIAS // USUARIOS*/
/*CREATE VIEW PUBLICACION_SERVICIOS 
AS
SELECT FECHA_INICIO, FECHA_FIN, ESTADO_DS, IMAGEN_SER, NOMBRE_SER, PRECIO_SER, TERMINOS_SER, NOMBRE_CAT, NOMBRE_USU, APELLIDOS_USU, CELULAR_USU, CORREO_ELECTRONICO, NOMBRE_CIUDAD
FROM
DETALLE_SERVICIOS INNER JOIN SERVICIOS 
ON DETALLE_SERVICIOS.ID_SERVICIO_FK = SERVICIOS.ID_SERVICIO 
INNER JOIN CATEGORIAS 
ON SERVICIOS.ID_CATEGORIA_FK = CATEGORIAS.ID_CATEGORIA
INNER JOIN USUARIOS
ON DETALLE_SERVICIOS.IDENTIFICACION_U_FK = USUARIOS.N_IDENTIFICACION
INNER JOIN CIUDAD
ON USUARIOS.ID_CIUDAD_FK = CIUDAD.ID_CIUDAD

/*PROCEDIMIENTO ALMACENADO CONSULTAR VISTA PUBLICACION SERVICIOS*/
CREATE PROCEDURE CONSULTAR_PUBLICACION
AS
BEGIN
	SELECT * FROM PUBLICACION_SERVICIOS
END

EXEC CONSULTAR_PUBLICACION
*/

/*PROCEDIMIENTO ALMACENADO PARA BUSCAR POR NOMBRE*/
CREATE PROCEDURE BUSQUEDAD_SERVICIOS(
@NOMBRE_SER VARCHAR(70))
AS
BEGIN
	SELECT NOMBRE_SER, PRECIO_SER,DESCRIPCION_BREVE, NOMBRE_CAT FROM 
	SERVICIOS INNER JOIN CATEGORIAS 
	ON SERVICIOS.ID_CATEGORIA_FK = CATEGORIAS.ID_CATEGORIA
	WHERE NOMBRE_SER LIKE '%'+@NOMBRE_SER+'%'
END

EXEC BUSQUEDAD_SERVICIOS 'Limpieza'

/*REINICIAR CONTADOR DEL ID*/
DBCC CHECKIDENT (CATEGORIAS, RESEED, 0)
