CREATE DATABASE SERVICE_MARKET
USE SERVICE_MARKET

/*CREACION DE LA TABLA ROLES*/
CREATE TABLE ROLES(
ID_ROL INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(40) NOT NULL)

/*CREACION DE LA TABLA USUARIOS*/
CREATE TABLE USUARIOS(
ID_USUARIO INT PRIMARY KEY IDENTITY(1,1),
IDENTIFICACION_U VARCHAR(15) NOT NULL,
TIPO_DOC VARCHAR(40) NOT NULL,
NOMBRE VARCHAR(60) NOT NULL,
APELLIDOS VARCHAR(70) NOT NULL,
CELULAR VARCHAR(12) NOT NULL,
CORREO_ELECTRONICO VARCHAR(100) NOT NULL,
CONTRASENA VARCHAR(500) NOT NULL,
FECHA_NACIMIENTO DATE NOT NULL,
ID_ROL_FK INT REFERENCES ROLES(ID_ROL))

/*PROCEDIMIENTO ALMACENADO PARA REGISTRAR USUARIOS*/
CREATE PROCEDURE REGISTRAR_USUARIO(
@IDENTIFICACION_U VARCHAR(15),
@TIPO_DOC VARCHAR(40),
@NOMBRE VARCHAR(60),
@APELLIDOS VARCHAR(70),
@CELULAR VARCHAR(12),
@CORREO_ELECTRONICO VARCHAR(100),
@CONTRASENA VARCHAR(500),
@FECHA_NACIMIENTO DATE,
@ID_ROL_FK INT,
@REGISTRADO BIT OUTPUT,
@MENSAJE VARCHAR(100) OUTPUT)
AS 
BEGIN
	IF(NOT EXISTS(SELECT * FROM USUARIOS WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO))
	BEGIN 
		INSERT INTO USUARIOS(IDENTIFICACION_U,TIPO_DOC,NOMBRE,APELLIDOS,CELULAR,CORREO_ELECTRONICO,CONTRASENA,FECHA_NACIMIENTO,ID_ROL_FK)
		VALUES (@IDENTIFICACION_U,@TIPO_DOC,@NOMBRE,@APELLIDOS,@CELULAR,@CORREO_ELECTRONICO,@CONTRASENA,@FECHA_NACIMIENTO,@ID_ROL_FK)
		SET @REGISTRADO = 1
		SET @MENSAJE = 'Usuario registrado'
	END
	ELSE
	BEGIN
		SET @REGISTRADO = 0
		SET @MENSAJE = 'Correo ya existe'
	END
END

/*PROCEDIMIENTO ALMACENADO PARA VALIDAR USUARIOS*/
CREATE PROCEDURE VALIDAR_USUARIO(
@CORREO_ELECTRONICO VARCHAR(100),
@CONTRASENA VARCHAR(500))
AS
BEGIN
	IF(EXISTS(SELECT * FROM USUARIOS WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO AND CONTRASENA = @CONTRASENA))
		SELECT ID_USUARIO FROM USUARIOS WHERE CORREO_ELECTRONICO = @CORREO_ELECTRONICO AND CONTRASENA = @CONTRASENA
	ELSE
		SELECT '0'
END

/*INSERT TABLA ROLES*/
INSERT INTO ROLES(NOMBRE) VALUES ('ADMINISTRADOR'),('PROVEEDOR')
INSERT INTO ROLES(NOMBRE) VALUES ('CLIENTE')
SELECT * FROM ROLES 

/*DECLARAR VARIABLES DE SALIDA*/
DECLARE @REGISTRADO BIT, @MENSAJE VARCHAR(100)

/*INSERT REGISTRAR USUARIO*/
EXEC REGISTRAR_USUARIO '1013376602','CEDULA DE CIUDADANIA','YESENIA','QUEJADA ROJAS','3135293264','yeyerojas1308@gmail.com','03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4','2004-01-13',1,@REGISTRADO OUTPUT,@MENSAJE OUTPUT
/*VALIDANDO REGISTRO*/
EXEC VALIDAR_USUARIO 'yeyerojas1308@gmail.com','03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4'

SELECT * FROM USUARIOS